ACHIEVEMENT = 1
LEARNING = 0
MULTIPLIER = 100
PER_GOOD_STUDENT = 30
PER_PERFECT_STUDENT = 50
DATABASE_PATH = 'data/auto-sys-database.sqlite'
ACHIEVEMENT_HEADER = ['Вид', 'Тип', 'Уровень', 'Место', 'Описание', 'Участники', 'Очки']
LEARNING_HEADER = ['Критерии', 'Кол-во', 'Ср.балл, кол-во', 'Очки']
LEARNING_CRITERIA = ['Ср. Балл по успеваемости', 'Отличники', 'Ударники']
MAIN_CRITERIA = ['Учёба', 'Внеурочная деятельность', 'Спорт', 'Активная жизненная позиция']
SETTINGS_HEADER = ['Аспект', 'Тип', 'Уровень', 'Место', 'Баллы']
FILTERS = ['По фамилии участника', 'По сфере']
